-- DATA SECURITY / SUPABASE SETUP
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  role text not null default 'user' check (role in ('user','admin')),
  disabled boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.files (
  id uuid primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  original_name text not null,
  storage_path text not null unique,
  description text not null default '',
  client_name text not null default '',
  category text not null default 'Other',
  tags text[] not null default '{}',
  mime_type text not null default 'application/octet-stream',
  size bigint not null default 0,
  sha256 text,
  is_trashed boolean not null default false,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.share_links (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  file_id uuid not null references public.files(id) on delete cascade,
  token_hash text not null unique,
  password_hash text,
  expires_at timestamptz,
  download_limit integer,
  download_count integer not null default 0,
  revoked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists files_owner_idx on public.files(owner_id, created_at desc);
create index if not exists files_trash_idx on public.files(owner_id, is_trashed);
create index if not exists clients_owner_idx on public.clients(owner_id);
create index if not exists activity_user_idx on public.activity_logs(user_id, created_at desc);
create index if not exists share_file_idx on public.share_links(file_id);

alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.files enable row level security;
alter table public.share_links enable row level security;
alter table public.activity_logs enable row level security;

-- Frontend only needs to read its own profile.
drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
on public.profiles for select
to authenticated
using (id = auth.uid());

-- These tables are accessed by the Render backend using service_role.
-- Explicitly revoke direct client table access to keep authorization centralized.
revoke all on public.profiles from anon, authenticated;
revoke all on public.clients from anon, authenticated;
revoke all on public.files from anon, authenticated;
revoke all on public.share_links from anon, authenticated;
revoke all on public.activity_logs from anon, authenticated;

grant select on public.profiles to authenticated;

-- Storage bucket.
insert into storage.buckets (id, name, public)
values ('user-files', 'user-files', false)
on conflict (id) do nothing;

-- Storage policies allow signed-in users to work only inside their own folder.
-- The app still registers metadata through the protected Render API.
drop policy if exists user_files_select_own on storage.objects;
create policy user_files_select_own
on storage.objects for select
to authenticated
using (
  bucket_id = 'user-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists user_files_insert_own on storage.objects;
create policy user_files_insert_own
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'user-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists user_files_update_own on storage.objects;
create policy user_files_update_own
on storage.objects for update
to authenticated
using (
  bucket_id = 'user-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'user-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists user_files_delete_own on storage.objects;
create policy user_files_delete_own
on storage.objects for delete
to authenticated
using (
  bucket_id = 'user-files'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

-- The Render service_role is never placed in browser code.
